name: Build & Deploy Flappy Bara

on:
  push:
    branches: [ main ]   # run when you push to main branch
  workflow_dispatch:     # allow manual trigger from Actions tab

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install pygbag
        run: pip install pygbag==0.9.3

      - name: Build game with pygbag
        working-directory: frontend/game   # 👈 updated path
        run: python -m pygbag --ume_block 0 --build main.py

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # 👇 point to the built web output
          path: frontend/game/build/web

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
