name: Build & Deploy Flappy Capy
on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install pygbag
        run: python -m pip install --upgrade pygbag

      - name: Build web with auto-start (ume_block=0)
        run: python -m pygbag --ume_block 0 --build main.py

      - name: Inject forwarder.js into build/web/index.html
        shell: bash
        run: |
          F="build/web/index.html"
          TAG='<script src="../../forwarder.js"></script>'
          if ! grep -q 'forwarder.js' "$F"; then
            awk -v tag="$TAG" '
              /<\/body>/ && !done { print "  <!-- injected: forwarder.js -->\n  " tag; done=1 }
              { print }
            ' "$F" > "$F.tmp" && mv "$F.tmp" "$F"
            echo "Injected forwarder.js"
          else
            echo "forwarder already injected"
          fi

      - name: Upload site (publish repo root so index.html + build/ are served)
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
