name: Build & Deploy Flappy Capy
on:
  push:
    branches: [ main ]   # change to master if your default branch is master

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Install pygbag (latest from GitHub)
      - name: Install pygbag
        run: |
          python -m pip install --upgrade pip
          python -m pip install "git+https://github.com/pygame-web/pygbag.git"

      # Install Emscripten toolchain for WebAssembly
      - name: Set up Emscripten (emsdk)
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: latest

      # Build the web bundle (creates build/web/* including .wasm/.data/.js)
      - name: Build with pygbag
        run: |
          python -m pygbag main.py
          ls -la build/web

      # Optional: patch the generated splash to auto-start on mobile
      - name: Auto-start patch (skip green overlay)
        run: |
          cat >> build/web/index.html <<'PATCH'
          <script>
          window.addEventListener("load", () => {
            const clickRun = () => {
              const btn = document.getElementById("run") || document.querySelector(".run, #start, .start, button");
              if (btn) try { btn.click(); } catch(e) {}
            };
            // try a few times in case elements mount late
            clickRun(); setTimeout(clickRun, 150); setTimeout(clickRun, 300);
          });
          </script>
          PATCH

      # Upload site artifact for GitHub Pages
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/web
